### ISSUE TITLE
"Type 5" nomogram not able to be computed.

### ISSUE THREAD

**Issue by neilbalch** [lefakkomies/pynomo#11]
I'm trying to plot a nomogram for the following [projectile motion](https://www.whitman.edu/Documents/Academics/Mathematics/2016/Henelsmith.pdf) function: `y = x * tan(theta) - 0.5g * x^2 / (4.236^2 * cos(theta)^2)` where `x` and `y` are the input parameters and `theta` is the output value of the nomogram. `g` is a constant 9.81 m/s^2.

I believe this problem to be a [Type 5](http://lefakkomies.github.io/pynomo-doc/types/types.html#type5-ref) nomogram.

The program I've written to try and plot this is as follows:

```python
import math
from pynomo.nomographer import *
import sys
import numpy
sys.path.insert(0, ".")

def x_expression(x, theta):
    #  x * tan(theta) - 0.5g * x^2 / (4.236^2 * cos(theta)^2)
    print("iteration")
    print("Type of x")
    print(type(x))
    if type(x) == numpy.ndarray:
        print("Type of x.item(0)")
        print(x.item(0))

        x = x.item(0).real

    print("Type of theta")
    print(type(theta))

    theta_r = math.radians(theta)
    output = x * math.tan(theta_r) - ((9.81 / 2) * math.pow(x, 2)) / \
        (math.pow(4.236, 2) * math.pow(math.cos(theta_r), 2))

    return output


# print(x_expression(1, 15))

# u: y-displacement in meters
# v: x-displacement in meters, theta in degrees
all_in_all_block = {
    'block_type': 'type_5',
    'u_func': lambda y: y,
    # 'v_func': lambda x, theta: math.pow(theta, 2),
    'v_func': lambda x, theta: x_expression(x, theta),
    # 'v_func': lambda x, theta: x * math.tan(math.radians(theta)) - ((9.81 / 2) * math.pow(x, 2)) / (math.pow(4.236, 2) * math.pow(math.cos(math.radians(theta)), 2)),
    'u_values': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
    'v_values': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
    'wd_tick_levels': 2,
    'wd_tick_text_levels': 1,
    'wd_tick_side': 'right',
    'wd_title': 'wd = u-v',
    'u_title': 'u: y-displacement (meters)',
    'v_title': 'v: x-displacement (meters)',
    'wd_title_opposite_tick': True,
    'wd_title_distance_center': 2.5,
    'isopleth_values': [[6.5, 7, 'x']],
}

main_params = {
    # 'filename': 'tutorial1a.eps',
    'filename': 'tutorial1a.pdf',
    'paper_height': 11.0,
    'paper_width': 8.5,
    'block_params': [all_in_all_block],
    'transformations': [('rotate', 0.01), ('scale paper',)],
    'title_str': r'\LARGE Trajectory calculator.',
}

Nomographer(main_params)
```

However, I must be missing something crucial, as this keeps coming up:

```shell
...
Type of theta
<class 'int'>
Traceback (most recent call last):
  File "nomoProjectile.py", line 64, in <module>
    Nomographer(main_params)
  File "/usr/local/lib/python3.6/dist-packages/pynomo/nomographer.py", line 224, in __init__
    isopleths.draw(c)
  File "/usr/local/lib/python3.6/dist-packages/pynomo/isopleth.py", line 147, in draw
    self._solve_()
  File "/usr/local/lib/python3.6/dist-packages/pynomo/isopleth.py", line 159, in _solve_
    isopleth.solve(self.solutions)
  File "/usr/local/lib/python3.6/dist-packages/pynomo/isopleth.py", line 992, in solve
    isopleth_values_single, idx)
  File "/usr/local/lib/python3.6/dist-packages/pynomo/isopleth.py", line 1049, in solve_single
    x_v, y_v, x_v_ini, y_v_ini = self.xy_v_u(isopleth_values[1], isopleth_values[0])
  File "/usr/local/lib/python3.6/dist-packages/pynomo/isopleth.py", line 1132, in xy_v_u
    for value in values_list_complex:
TypeError: 'float' object is not iterable
```

I'm not sure what's going on here... can anyone help me out?

**Comment by lefakkomies** [comment]
Also Pynomo type_5 example fails so there is probably something changed in NumPy.

**Comment by neilbalch** [comment]
Interesting... @lefakkomies, because it didn't for me. The example worked fine when I ran it.

**Comment by lefakkomies** [comment]
Now should work with at least 
numpy==1.17.2
PyX==0.15
scipy==1.2.0

**Comment by lefakkomies** [comment]
```python
from pynomo.nomographer import *

import numpy as np

def x_expression(x, theta):
    #  x * tan(theta) - 0.5g * x^2 / (4.236^2 * cos(theta)^2)
    print("iteration")
    print("Type of x")
    print(type(x))
    if type(x) == np.ndarray:
        print("Type of x.item(0)")
        print(x.item(0))
        x = x.item(0).real
    print("Type of theta")
    print(type(theta))
    theta_r = np.radians(theta)
    output = x * np.tan(theta_r) - ((9.81 / 2) * np.power(x, 2)) / \
        (np.power(4.236, 2) * np.power(np.cos(theta_r), 2))
    return output

# print(x_expression(1, 15))
# u: y-displacement in meters
# v: x-displacement in meters, theta in degrees
all_in_all_block = {
    'block_type': 'type_5',
    'u_func': lambda y: y,
    # 'v_func': lambda x, theta: math.pow(theta, 2),
    'v_func': lambda x, theta: x_expression(x, theta),
    # 'v_func': lambda x, theta: x * math.tan(math.radians(theta)) - ((9.81 / 2) * math.pow(x, 2)) / (math.pow(4.236, 2) * math.pow(math.cos(math.radians(theta)), 2)),
    'u_values': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
    'v_values': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
    'wd_tick_levels': 2,
    'wd_tick_text_levels': 1,
    'wd_tick_side': 'right',
    'wd_title': 'wd = u-v',
    'u_title': 'u: y-displacement (meters)',
    'v_title': 'v: x-displacement (meters)',
    'wd_title_opposite_tick': True,
    'wd_title_distance_center': 2.5,
    'isopleth_values': [[6.5, 7, 'x']],
}

main_params = {
    # 'filename': 'tutorial1a.eps',
    'filename': 'tutorial1a.pdf',
    'paper_height': 11.0,
    'paper_width': 8.5,
    'block_params': [all_in_all_block],
    'transformations': [('rotate', 0.01), ('scale paper',)],
    'title_str': r'\LARGE Trajectory calculator.',
}
Nomographer(main_params)
```

This should now at least run and generate pdf. 

I pushed new version of pynomo to python package index (pypi)

**Comment by neilbalch** [comment]
Hrm, this does run without exceptions, but it doesn't produce any content in the PDF... Nothing.
[nomoProjectile.pdf](https://github.com/lefakkomies/pynomo/files/3587892/nomoProjectile.pdf)

**Comment by lefakkomies** [comment]
I can see content in this pdf. At least in Mac preview?

**Comment by neilbalch** [comment]
Sorry, working mistake. There's content, but no lines on the plot like I expected to see. 
![image](https://user-images.githubusercontent.com/3847882/64492794-0887f580-d22d-11e9-900d-087e19dc681c.png)
