### ISSUE TITLE
ex_compound_nomo_2.py broken ?

### ISSUE THREAD

**Issue by daturach** [lefakkomies/pynomo#12]
Thanks for this great software. I just installed it and managed to create a nomogram (Ohm's Law), quite basic but rewarding enough!
Now, need to tackle the determinant section. It's quite steep.
Anyway, I could not generate "ex_compound_nomo_2.py" with python 2.7.12 from the example section.
`Traceback (most recent call last):
  File "ex_compound_nomo_2.py", line 160, in <module>
    Nomographer(main_params)
  File "/usr/local/lib/python2.7/dist-packages/pynomo/nomographer.py", line 82, in __init__
    height=block_para['height'])
  File "/usr/local/lib/python2.7/dist-packages/pynomo/nomo_wrapper.py", line 1012, in set_block
    length_f1_ini = max(self.F1(self.params_F1['u_min']), self.F1(self.params_F1['u_max'])) - \
  File "ex_compound_nomo_2.py", line 30, in <lambda>
    'function': lambda u: log(u),
NameError: global name 'log' is not defined
`

Walter

**Comment by lefakkomies** [comment]
Added 
`from math import log`
to the example and committed the change.
