### ISSUE TITLE
Empty PDF

### ISSUE THREAD

**Issue by RichRayHard** [lefakkomies/pynomo#14]
I have used Pynomo on older machines in the past. Tried installing on new machine only to encounter various problems with Python 2.6 and Python 3. Current install is on Python 2.7 numpy 1.16.6 PyX 0.12.1 Pynomo 0.3.2

When I run a test pynomo script a pdf is made that is empty. Command Prompt traceback is copied below. I've run to the end of what I'm able to do myself without asking for help. I would appreciate any help. Thanks

C:\Users\Richard\Documents\Pynomo>python retainingwall.py
Traceback (most recent call last):
  File "retainingwall.py", line 84, in <module>
    Nomographer(main_params)
  File "C:\Python27\lib\site-packages\pynomo\nomographer.py", line 232, in __init__
    wrapper.draw_nomogram(c, params['post_func'])
  File "C:\Python27\lib\site-packages\pynomo\nomo_wrapper.py", line 268, in draw_nomogram
    canvas.writePDFfile(self.filename)
  File "C:\Python27\lib\site-packages\pyx\canvas.py", line 48, in wrappedindocument
    return method(d, file, **write_kwargs)
  File "C:\Python27\lib\site-packages\pyx\document.py", line 171, in writePDFfile
    pdfwriter.PDFwriter(self, _outputstream(file, "pdf"), **kwargs)
  File "C:\Python27\lib\site-packages\pyx\pdfwriter.py", line 316, in __init__
    catalog = PDFcatalog(document, self, registry)
  File "C:\Python27\lib\site-packages\pyx\pdfwriter.py", line 142, in __init__
    self.PDFpages = PDFpages(document, writer, registry)
  File "C:\Python27\lib\site-packages\pyx\pdfwriter.py", line 201, in __init__
    page = PDFpage(page, pageno, self, writer, registry)
  File "C:\Python27\lib\site-packages\pyx\pdfwriter.py", line 235, in __init__
    self.PDFcontent = PDFcontent(page, writer, self.pageregistry)
  File "C:\Python27\lib\site-packages\pyx\pdfwriter.py", line 267, in __init__
    page.processPDF(contentfile, writer, acontext, registry, self.bbox)
  File "C:\Python27\lib\site-packages\pyx\document.py", line 132, in processPDF
    self._process("processPDF", *args)
  File "C:\Python27\lib\site-packages\pyx\document.py", line 126, in _process
    getattr(cc, processMethod)(contentfile, writer, context, registry, bbox)
  File "C:\Python27\lib\site-packages\pyx\canvas.py", line 199, in processPDF
    item.processPDF(file, writer, context, registry, nbbox)
  File "C:\Python27\lib\site-packages\pyx\text.py", line 733, in processPDF
    self.ensuredvicanvas()
  File "C:\Python27\lib\site-packages\pyx\text.py", line 705, in ensuredvicanvas
    self.finishdvi()
  File "C:\Python27\lib\site-packages\pyx\text.py", line 1042, in finishdvi
    self.execute(None, self.defaulttexmessagesend + self.texmessagesend)
  File "C:\Python27\lib\site-packages\pyx\text.py", line 1034, in execute
    raise TexResultError("unhandled TeX response (might be an error)", self)
pyx.text.TexResultError: unhandled TeX response (might be an error)
The expression passed to TeX was:
  \end%
After parsing the return message from TeX, the following was left:
  *

  tex: major issue: So far, no MiKTeX administrator has checked for updates.

**Comment by lefakkomies** [comment]
This is pyx/TeX problem and outside Pynomo. Try running pyx examples that Pynomo relies on.
