### ISSUE TITLE
ModuleNotFoundError: No module named 'nomo_wrapper'

### ISSUE THREAD

**Issue by adam-funk** [lefakkomies/pynomo#7]
Hi,
I've tried installing pynomo using pip3 as well as git clone + "python3 setup.py install --user", but I can't get past this:

$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynomo.nomographer import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adam/.local/lib/python3.6/site-packages/PyNomo-0.3.0-py3.6.egg/pynomo/nomographer.py", line 16, in <module>
ModuleNotFoundError: No module named 'nomo_wrapper'

Any idea what I'm doing wrong?

**Comment by lefakkomies** [comment]
Did you check which packages exist in your installation directory:
home/adam/.local/lib/python3.6/site-packages/PyNomo-0.3.0-py3.6.egg/pynomo/
There should be file nomo_wrapper.py ?

**Comment by adam-funk** [comment]
I have a file '.../site-packages/PyNomo-0.3.0-py3.6.egg' and a directory 'site-packages/PyNomo-0.3.0.dist-info' but no subdirectories of them.  The egg file has 'pynomo/nomo_wrapper.py' (and others) zipped up inside.

**Comment by adam-funk** [comment]
Yes, that's the problem. It does work for me in Python 2.
Thanks.

**Comment by adam-funk** [comment]
Great, thanks!
